version: '3'
services:
  moses-en-is:
    image: haukurp/moses-smt:final-en-is
    ports:
      - "8081:8080"
    command: /opt/moses/bin/moses -threads 2 -f /work/moses.ini --server
  moses-is-en:
    image: haukurp/moses-smt:final-is-en
    ports:
      - "8082:8080"
    command: /opt/moses/bin/moses -threads 2 -f /work/moses.ini --server
  proxy:
    image: haukurp/moses-lvl:3.0.1
    links:
      - moses-en-is
      - moses-is-en
    environment:
      - MODEL_en_is_moses=http://moses-en-is:8080/RPC2
      - MODEL_is_en_moses=http://moses-is-en:8080/RPC2
    ports:
      - "5000:5000"