version: '3'
services:
  moses-en-is:
    image: haukurp/moses-smt:en-is-improved
    ports:
      - "8081:8080"
    command: /opt/moses/bin/moses -threads 2 -f /work/moses.ini --server
  moses-is-en:
    image: haukurp/moses-smt:is-en-improved
    ports:
      - "8082:8080"
    command: /opt/moses/bin/moses -threads 2 -f /work/moses.ini --server
  frontend:
    image: haukurp/moses-lvl:2.0.8
    links:
      - moses-en-is
      - moses-is-en
    environment:
      - MODEL_en_is=http://moses-en-is:8080/RPC2
      - MODEL_is_en=http://moses-is-en:8080/RPC2
      - PREPROCESSING_en_is=v2
      - PREPROCESSING_is_en=v2
    ports:
      - "5000:5000"
    command: frontend server --debug