version: '3'
services:
  moses-en-is:
    image: haukurp/moses-smt:en-is
    ports:
      - "8080:8080"
    command: /opt/moses/bin/moses -threads 4 -f /work/moses.ini --server
  moses-is-en:
    image: haukurp/moses-smt:is-en
    ports:
      - "8081:8080"
    command: /opt/moses/bin/moses -threads 4 -f /work/moses.ini --server
  frontend:
    image: haukurp/moses-lvl:2.0.2
    ports:
      - "80:5000"
    command: frontend server --debug